### ISSUE TITLE
dx tool failed

### ISSUE THREAD

**Issue by linusn** [myflashlab/facebook-ANE#82]
Hi,

I'm getting an error when trying to run on an Android Device via Intellij. I'm using **AIR SDK 25** and downloaded the `androidSupport.ane` from https://drive.google.com/file/d/0B7eHG2CEml2TVXJETEs5SGNSUTg/view?usp=sharing (link found in https://github.com/myflashlab/facebook-ANE/issues/79)

The error:
```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$anim;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
	at com.android.dx.command.dexer.Main.run(Main.java:247)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting
```

**Comment by sftcr** [comment]
This could be a conflict with another ANE. If you are using distriqt ANEs try to use com.distriqt.Core.noair.ane instead of com.distriqt.Core.ane. You can find this here [https://github.com/distriqt/ANE-Core](url).

**Comment by linusn** [comment]
Solved! The problem was a combination of my inexperience and a tight deadline. I'm sure many can relate. ;)

Some of the settings in the manifest were missing, and I was using the AIR SDK 24.

**Comment by myflashlab** [comment]
Good to know that. we were totally puzzeled when you suggested the dx tool fail and using AIR 25! because AIR 25 has fixed that problem by introducing multiDex support.
